name: research_code_push_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0+2

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mocktail: ^1.0.4

flutter:
  assets:
    - shorebird.yaml
    - assets/images/
  uses-material-design: true
